// All world countries with ISO 3166-1 alpha-2 codes, calling codes, and currency codes.
// Flags are computed from the alpha-2 code via regional indicator symbols.

const RAW = [
  ['Afghanistan', 'AF', '93', 'AFN'],
  ['Albania', 'AL', '355', 'ALL'],
  ['Algeria', 'DZ', '213', 'DZD'],
  ['American Samoa', 'AS', '1684', 'USD'],
  ['Andorra', 'AD', '376', 'EUR'],
  ['Angola', 'AO', '244', 'AOA'],
  ['Anguilla', 'AI', '1264', 'XCD'],
  ['Antigua and Barbuda', 'AG', '1268', 'XCD'],
  ['Argentina', 'AR', '54', 'ARS'],
  ['Armenia', 'AM', '374', 'AMD'],
  ['Aruba', 'AW', '297', 'AWG'],
  ['Australia', 'AU', '61', 'AUD'],
  ['Austria', 'AT', '43', 'EUR'],
  ['Azerbaijan', 'AZ', '994', 'AZN'],
  ['Bahamas', 'BS', '1242', 'BSD'],
  ['Bahrain', 'BH', '973', 'BHD'],
  ['Bangladesh', 'BD', '880', 'BDT'],
  ['Barbados', 'BB', '1246', 'BBD'],
  ['Belarus', 'BY', '375', 'BYN'],
  ['Belgium', 'BE', '32', 'EUR'],
  ['Belize', 'BZ', '501', 'BZD'],
  ['Benin', 'BJ', '229', 'XOF'],
  ['Bermuda', 'BM', '1441', 'BMD'],
  ['Bhutan', 'BT', '975', 'BTN'],
  ['Bolivia', 'BO', '591', 'BOB'],
  ['Bonaire, Sint Eustatius and Saba', 'BQ', '599', 'USD'],
  ['Bosnia and Herzegovina', 'BA', '387', 'BAM'],
  ['Botswana', 'BW', '267', 'BWP'],
  ['Brazil', 'BR', '55', 'BRL'],
  ['Brunei Darussalam', 'BN', '673', 'BND'],
  ['Bulgaria', 'BG', '359', 'BGN'],
  ['Burkina Faso', 'BF', '226', 'XOF'],
  ['Burundi', 'BI', '257', 'BIF'],
  ['Cabo Verde', 'CV', '238', 'CVE'],
  ['Cambodia', 'KH', '855', 'KHR'],
  ['Cameroon', 'CM', '237', 'XAF'],
  ['Canada', 'CA', '1', 'CAD'],
  ['Cayman Islands', 'KY', '1345', 'KYD'],
  ['Central African Republic', 'CF', '236', 'XAF'],
  ['Chad', 'TD', '235', 'XAF'],
  ['Chile', 'CL', '56', 'CLP'],
  ['China', 'CN', '86', 'CNY'],
  ['Colombia', 'CO', '57', 'COP'],
  ['Comoros', 'KM', '269', 'KMF'],
  ['Congo', 'CG', '242', 'XAF'],
  ['Congo (Democratic Republic)', 'CD', '243', 'CDF'],
  ['Cook Islands', 'CK', '682', 'NZD'],
  ['Costa Rica', 'CR', '506', 'CRC'],
  ["Côte d'Ivoire", 'CI', '225', 'XOF'],
  ['Croatia', 'HR', '385', 'EUR'],
  ['Cuba', 'CU', '53', 'CUP'],
  ['Curaçao', 'CW', '599', 'ANG'],
  ['Cyprus', 'CY', '357', 'EUR'],
  ['Czechia', 'CZ', '420', 'CZK'],
  ['Denmark', 'DK', '45', 'DKK'],
  ['Djibouti', 'DJ', '253', 'DJF'],
  ['Dominica', 'DM', '1767', 'XCD'],
  ['Dominican Republic', 'DO', '1809', 'DOP'],
  ['Ecuador', 'EC', '593', 'USD'],
  ['Egypt', 'EG', '20', 'EGP'],
  ['El Salvador', 'SV', '503', 'USD'],
  ['Equatorial Guinea', 'GQ', '240', 'XAF'],
  ['Eritrea', 'ER', '291', 'ERN'],
  ['Estonia', 'EE', '372', 'EUR'],
  ['Eswatini', 'SZ', '268', 'SZL'],
  ['Ethiopia', 'ET', '251', 'ETB'],
  ['Falkland Islands', 'FK', '500', 'FKP'],
  ['Faroe Islands', 'FO', '298', 'DKK'],
  ['Fiji', 'FJ', '679', 'FJD'],
  ['Finland', 'FI', '358', 'EUR'],
  ['France', 'FR', '33', 'EUR'],
  ['French Guiana', 'GF', '594', 'EUR'],
  ['French Polynesia', 'PF', '689', 'XPF'],
  ['Gabon', 'GA', '241', 'XAF'],
  ['Gambia', 'GM', '220', 'GMD'],
  ['Georgia', 'GE', '995', 'GEL'],
  ['Germany', 'DE', '49', 'EUR'],
  ['Ghana', 'GH', '233', 'GHS'],
  ['Gibraltar', 'GI', '350', 'GIP'],
  ['Greece', 'GR', '30', 'EUR'],
  ['Greenland', 'GL', '299', 'DKK'],
  ['Grenada', 'GD', '1473', 'XCD'],
  ['Guadeloupe', 'GP', '590', 'EUR'],
  ['Guam', 'GU', '1671', 'USD'],
  ['Guatemala', 'GT', '502', 'GTQ'],
  ['Guernsey', 'GG', '44', 'GBP'],
  ['Guinea', 'GN', '224', 'GNF'],
  ['Guinea-Bissau', 'GW', '245', 'XOF'],
  ['Guyana', 'GY', '592', 'GYD'],
  ['Haiti', 'HT', '509', 'HTG'],
  ['Honduras', 'HN', '504', 'HNL'],
  ['Hong Kong', 'HK', '852', 'HKD'],
  ['Hungary', 'HU', '36', 'HUF'],
  ['Iceland', 'IS', '354', 'ISK'],
  ['India', 'IN', '91', 'INR'],
  ['Indonesia', 'ID', '62', 'IDR'],
  ['Iran', 'IR', '98', 'IRR'],
  ['Iraq', 'IQ', '964', 'IQD'],
  ['Ireland', 'IE', '353', 'EUR'],
  ['Isle of Man', 'IM', '44', 'GBP'],
  ['Israel', 'IL', '972', 'ILS'],
  ['Italy', 'IT', '39', 'EUR'],
  ['Jamaica', 'JM', '1876', 'JMD'],
  ['Japan', 'JP', '81', 'JPY'],
  ['Jersey', 'JE', '44', 'GBP'],
  ['Jordan', 'JO', '962', 'JOD'],
  ['Kazakhstan', 'KZ', '7', 'KZT'],
  ['Kenya', 'KE', '254', 'KES'],
  ['Kiribati', 'KI', '686', 'AUD'],
  ['Kuwait', 'KW', '965', 'KWD'],
  ['Kyrgyzstan', 'KG', '996', 'KGS'],
  ["Laos (Lao People's Democratic Republic)", 'LA', '856', 'LAK'],
  ['Latvia', 'LV', '371', 'EUR'],
  ['Lebanon', 'LB', '961', 'LBP'],
  ['Lesotho', 'LS', '266', 'LSL'],
  ['Liberia', 'LR', '231', 'LRD'],
  ['Libya', 'LY', '218', 'LYD'],
  ['Liechtenstein', 'LI', '423', 'CHF'],
  ['Lithuania', 'LT', '370', 'EUR'],
  ['Luxembourg', 'LU', '352', 'EUR'],
  ['Macao', 'MO', '853', 'MOP'],
  ['Madagascar', 'MG', '261', 'MGA'],
  ['Malawi', 'MW', '265', 'MWK'],
  ['Malaysia', 'MY', '60', 'MYR'],
  ['Maldives', 'MV', '960', 'MVR'],
  ['Mali', 'ML', '223', 'XOF'],
  ['Malta', 'MT', '356', 'EUR'],
  ['Marshall Islands', 'MH', '692', 'USD'],
  ['Martinique', 'MQ', '596', 'EUR'],
  ['Mauritania', 'MR', '222', 'MRU'],
  ['Mauritius', 'MU', '230', 'MUR'],
  ['Mayotte', 'YT', '262', 'EUR'],
  ['Mexico', 'MX', '52', 'MXN'],
  ['Micronesia', 'FM', '691', 'USD'],
  ['Moldova', 'MD', '373', 'MDL'],
  ['Monaco', 'MC', '377', 'EUR'],
  ['Mongolia', 'MN', '976', 'MNT'],
  ['Montenegro', 'ME', '382', 'EUR'],
  ['Montserrat', 'MS', '1664', 'XCD'],
  ['Morocco', 'MA', '212', 'MAD'],
  ['Mozambique', 'MZ', '258', 'MZN'],
  ['Myanmar', 'MM', '95', 'MMK'],
  ['Namibia', 'NA', '264', 'NAD'],
  ['Nauru', 'NR', '674', 'AUD'],
  ['Nepal', 'NP', '977', 'NPR'],
  ['Netherlands', 'NL', '31', 'EUR'],
  ['New Caledonia', 'NC', '687', 'XPF'],
  ['New Zealand', 'NZ', '64', 'NZD'],
  ['Nicaragua', 'NI', '505', 'NIO'],
  ['Niger', 'NE', '227', 'XOF'],
  ['Nigeria', 'NG', '234', 'NGN'],
  ['Niue', 'NU', '683', 'NZD'],
  ['North Korea', 'KP', '850', 'KPW'],
  ['North Macedonia', 'MK', '389', 'MKD'],
  ['Northern Mariana Islands', 'MP', '1670', 'USD'],
  ['Norway', 'NO', '47', 'NOK'],
  ['Oman', 'OM', '968', 'OMR'],
  ['Pakistan', 'PK', '92', 'PKR'],
  ['Palau', 'PW', '680', 'USD'],
  ['Palestine', 'PS', '970', 'ILS'],
  ['Panama', 'PA', '507', 'PAB'],
  ['Papua New Guinea', 'PG', '675', 'PGK'],
  ['Paraguay', 'PY', '595', 'PYG'],
  ['Peru', 'PE', '51', 'PEN'],
  ['Philippines', 'PH', '63', 'PHP'],
  ['Pitcairn', 'PN', '64', 'NZD'],
  ['Poland', 'PL', '48', 'PLN'],
  ['Portugal', 'PT', '351', 'EUR'],
  ['Puerto Rico', 'PR', '1787', 'USD'],
  ['Qatar', 'QA', '974', 'QAR'],
  ['Réunion', 'RE', '262', 'EUR'],
  ['Romania', 'RO', '40', 'RON'],
  ['Russia', 'RU', '7', 'RUB'],
  ['Rwanda', 'RW', '250', 'RWF'],
  ['Saint Barthélemy', 'BL', '590', 'EUR'],
  ['Saint Helena', 'SH', '290', 'SHP'],
  ['Saint Kitts and Nevis', 'KN', '1869', 'XCD'],
  ['Saint Lucia', 'LC', '1758', 'XCD'],
  ['Saint Martin', 'MF', '590', 'EUR'],
  ['Saint Pierre and Miquelon', 'PM', '508', 'EUR'],
  ['Saint Vincent and the Grenadines', 'VC', '1784', 'XCD'],
  ['Samoa', 'WS', '685', 'WST'],
  ['San Marino', 'SM', '378', 'EUR'],
  ['Sao Tome and Principe', 'ST', '239', 'STN'],
  ['Saudi Arabia', 'SA', '966', 'SAR'],
  ['Senegal', 'SN', '221', 'XOF'],
  ['Serbia', 'RS', '381', 'RSD'],
  ['Seychelles', 'SC', '248', 'SCR'],
  ['Sierra Leone', 'SL', '232', 'SLL'],
  ['Singapore', 'SG', '65', 'SGD'],
  ['Sint Maarten', 'SX', '1721', 'ANG'],
  ['Slovakia', 'SK', '421', 'EUR'],
  ['Slovenia', 'SI', '386', 'EUR'],
  ['Solomon Islands', 'SB', '677', 'SBD'],
  ['Somalia', 'SO', '252', 'SOS'],
  ['South Africa', 'ZA', '27', 'ZAR'],
  ['South Korea', 'KR', '82', 'KRW'],
  ['South Sudan', 'SS', '211', 'SSP'],
  ['Spain', 'ES', '34', 'EUR'],
  ['Sri Lanka', 'LK', '94', 'LKR'],
  ['Sudan', 'SD', '249', 'SDG'],
  ['Suriname', 'SR', '597', 'SRD'],
  ['Sweden', 'SE', '46', 'SEK'],
  ['Switzerland', 'CH', '41', 'CHF'],
  ['Syria', 'SY', '963', 'SYP'],
  ['Taiwan', 'TW', '886', 'TWD'],
  ['Tajikistan', 'TJ', '992', 'TJS'],
  ['Tanzania', 'TZ', '255', 'TZS'],
  ['Thailand', 'TH', '66', 'THB'],
  ['Timor-Leste', 'TL', '670', 'USD'],
  ['Togo', 'TG', '228', 'XOF'],
  ['Tokelau', 'TK', '690', 'NZD'],
  ['Tonga', 'TO', '676', 'TOP'],
  ['Trinidad and Tobago', 'TT', '1868', 'TTD'],
  ['Tunisia', 'TN', '216', 'TND'],
  ['Turkey', 'TR', '90', 'TRY'],
  ['Turkmenistan', 'TM', '993', 'TMT'],
  ['Turks and Caicos Islands', 'TC', '1649', 'USD'],
  ['Tuvalu', 'TV', '688', 'AUD'],
  ['Uganda', 'UG', '256', 'UGX'],
  ['Ukraine', 'UA', '380', 'UAH'],
  ['United Arab Emirates', 'AE', '971', 'AED'],
  ['United Kingdom', 'GB', '44', 'GBP'],
  ['United States', 'US', '1', 'USD'],
  ['Uruguay', 'UY', '598', 'UYU'],
  ['Uzbekistan', 'UZ', '998', 'UZS'],
  ['Vanuatu', 'VU', '678', 'VUV'],
  ['Vatican City', 'VA', '39', 'EUR'],
  ['Venezuela', 'VE', '58', 'VES'],
  ['Vietnam', 'VN', '84', 'VND'],
  ['Virgin Islands (British)', 'VG', '1284', 'USD'],
  ['Virgin Islands (US)', 'VI', '1340', 'USD'],
  ['Wallis and Futuna', 'WF', '681', 'XPF'],
  ['Western Sahara', 'EH', '212', 'MAD'],
  ['Yemen', 'YE', '967', 'YER'],
  ['Zambia', 'ZM', '260', 'ZMW'],
  ['Zimbabwe', 'ZW', '263', 'ZWL'],
];

export const COUNTRIES = RAW.map(([name, code, dialCode, currency]) => ({
  name,
  code,
  dialCode,
  currency,
}));

export const flagFromCode = (code) =>
  code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));

export const findCountry = (value) =>
  COUNTRIES.find((c) => c.name === value || c.code === value);